version: 2
machine:
  timezone: Europe/Helsinki

jobs:
  test:
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install --no-progress --no-save
      - save_cache:
          key: v1-deps-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Start server
          command: npm start
          background: true
      - run:
          name: Waiting for server to start
          command: |
            for i in {1..10}
            do
              if $(nc -z localhost 8080)
              then
                echo "Server is running"
                break
              else
                echo "Server is not running"
                sleep 1s
              fi
            done

            nc -vz localhost 8080
      - run:
          name: Update screenshots
          command: npm test
      - run:
          name: Setup git
          command: |
            git config --global user.name $PUSHBACK_USER_NAME
            git config --global user.email $PUSHBACK_USER_EMAIL
            git remote add pushback https://$PUSHBACK_TOKEN@github.com/janivihervas/visual-regression-test-example.git
      - run:
          name: Check if test files changed
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "AUTOMATIC BOT: Screenshots"
              fi
            fi
      - run:
          name: Cancel build if there are autobot fixes
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              if [[ $(git log origin/$CIRCLE_BRANCH..$CIRCLE_BRANCH) ]]; then
                echo AUTOBOT FIX
                git push --set-upstream pushback $CIRCLE_BRANCH
                exit 1
              fi
            fi

workflows:
  version: 2
  ci:
    jobs:
      - test
